
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  adapter: postgresql
  encoding: unicode
  database: sep24
  pool: 5


test:
  <<: *default
  database: nakedandafraid_test


#
production:
  primary: &primary_production
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

  cache:
    <<: *primary_production
    migrations_paths: db/cache_migrate
    database_tasks: false

  queue:
    <<: *primary_production
    migrations_paths: db/queue_migrate
    database_tasks: false

  cable:
    <<: *primary_production
    migrations_paths: db/cable_migrate
    database_tasks: false
