module ApplicationHelper
  def format_duration(seconds)
    return "—" if seconds.blank? || seconds <= 0
    mins = seconds.to_i / 60
    secs = seconds.to_i % 60
    mins > 0 ? "#{mins}m #{secs}s" : "#{secs}s"
  end

  def item_icon(item)
    name = item.is_a?(String) ? item : item&.name.to_s
    case name
    when /\A\?\z/                            then "❓"
    when /axe|tomahawk|hatchet|pulaski/      then "🪓"
    when /sword/                             then "⚔️"
    when /saw/                               then "🪚"
    when /knife|machete|kukri|blade/         then "🔪"
    when /pan/                               then "🍳"
    when /pot|pottery/                       then "🍲"
    when /blow\s*gun/                        then "🪈"
    when /bow drill/                         then "🔥"
    when /permanganate/                      then "🔥"
    when /magnif|glass.*lens/                then "🔍"
    when /fire|lighter|flint/                then "🔥"
    when /\bbow\b|arrow/                     then "🏹"
    when /spear|atlatl|dart/                 then "🗡️"
    when /sling/                             then "🎯"
    when /snare/                             then "🪤"
    when /hook/                              then "🪝"
    when /cast.*net/                         then "🕸️"
    when /snorkel|diving mask|scuba/         then "🤿"
    when /goggle/                            then "🥽"
    when /\bfins?\b/                         then "🤿"
    when /slack\s*line/                      then "🪢"
    when /fish|line(?!n)/                    then "🎣"
    when /rope/                              then "🪢"
    when /cord|string|paracord/              then "🪢"
    when /hammock/                           then "🛏️"
    when /tent/                              then "⛺"
    when /tarp/                              then "🛖"
    when /shelter/                           then "🛖"
    when /duct/                              then "🩹"
    when /mosquito/                          then "🦟"
    when /\bhide\b|pelt|skin|\bfurs?\b/      then "🦌"
    when /shovel/                            then "⛏️"
    when /boat/                              then "🛶"
    when /paddle/                            then "🛶"
    when /fabric|cloth/                      then "🧵"
    when /flash\s*light|torch/               then "🔦"
    when /bailer|bucket/                     then "🪣"
    when /lens/                              then "🔍"
    when /mask/                              then "🤿"
    # ----- Animals -----
    when /snake|python|cobra|viper|boa/      then "🐍"
    when /lizard|iguana|gecko/               then "🦎"
    when /caiman|crocodile|alligator/        then "🐊"
    when /turtle|tortoise/                   then "🐢"
    when /frog|toad/                         then "🐸"
    when /crab/                              then "🦀"
    when /lobster/                           then "🦞"
    when /shrimp/                            then "🦐"
    when /clam|mussel|oyster|conch/          then "🐚"
    when /snail|slug/                        then "🐌"
    when /shark/                             then "🦈"
    when /octopus|squid/                     then "🐙"
    when /jellyfish/                         then "🪼"
    when /eel/                               then "🐟"
    when /fish|piranha|trout|bass|tilapia|catfish|perch/ then "🐟"
    when /bird|chicken|duck|goose|pigeon|dove|parrot/    then "🐦"
    when /pig|boar|hog/                      then "🐗"
    when /deer|elk/                          then "🦌"
    when /goat/                              then "🐐"
    when /rabbit/                            then "🐇"
    when /rat|mouse/                         then "🐀"
    when /monkey/                            then "🐒"
    when /bear/                              then "🐻"
    when /wolf|coyote|fox/                   then "🐺"
    when /jaguar|puma|leopard|lion/          then "🐆"
    when /scorpion/                          then "🦂"
    when /spider/                            then "🕷️"
    when /ant|termite/                       then "🐜"
    when /beetle/                            then "🪲"
    when /cricket|grasshopper/               then "🦗"
    when /worm|grub|larvae|maggot/           then "🪱"
    when /bug|insect/                        then "🐛"
    when /animal/                            then "🐾"
    # ----- Plants -----
    when /coconut/                           then "🥥"
    when /banana/                            then "🍌"
    when /mango|papaya|guava|passion\s*fruit|jackfruit|breadfruit|pineapple/ then "🥭"
    when /berry|berries/                     then "🫐"
    when /fruit/                             then "🍈"
    when /mushroom|fungus|fungi/             then "🍄"
    when /yam|taro|cassava|potato|tuber|root/ then "🥔"
    when /corn/                              then "🌽"
    when /rice|grain/                        then "🌾"
    when /bean|lentil/                       then "🫘"
    when /nut/                               then "🥜"
    when /seed/                              then "🌱"
    when /bamboo/                            then "🎋"
    when /cactus/                            then "🌵"
    when /palm/                              then "🌴"
    when /seaweed|kelp|algae/                then "🌿"
    when /herb|mint|basil|sage/              then "🌿"
    when /flower/                            then "🌺"
    when /plant|leaf|leaves|vine|bark|grass|reed|cattail/ then "🌿"
    else
      type = item.respond_to?(:item_type) ? (item.item_type rescue nil) : nil
      case type
      when "blade"              then "🔪"
      when "pot"                then "🍲"
      when "fire starting tool" then "🔥"
      when "hunting weapon"     then "🏹"
      when "fishing tool"       then "🎣"
      when "cordage"            then "🪢"
      when "comfort item"       then "🛖"
      when "digging tool"       then "⛏️"
      when "animal"             then "🐾"
      when "plant"              then "🌿"
      else "🔧"
      end
    end
  end
end
